name: SWF
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - cffi=1.14.0=py37h2e261b9_0
  - cudatoolkit=9.2=0
  - cudnn=7.6.5=cuda9.2_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2020.0=166
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1e=h7b6447c_0
  - pillow=6.1.0=py37h34e0f95_0
  - pip=20.0.2=py37_1
  - pycparser=2.20=py_0
  - python=3.7.6=h0371630_2
  - pytorch=1.4.0=cuda92py37h488537e_0
  - readline=7.0=h7b6447c_5
  - setuptools=46.0.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.1=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.3
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - importlib-metadata==1.5.0
    - ipykernel==5.2.0
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.16.0
    - jinja2==2.11.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.0
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - kiwisolver==1.1.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - notebook==6.0.3
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.4
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyzmq==19.0.0
    - git+https://github.com/aliutkus/qsketch.git
    - qtconsole==4.7.1
    - qtpy==1.9.0
    - scipy==1.4.1
    - seaborn==0.10.0
    - send2trash==1.5.0
    - terminado==0.8.3
    - testpath==0.4.4
    - torch==1.4.0
    - git+https://github.com/aliutkus/torchinterp1d.git
    - git+https://github.com/aliutkus/torchpercentile.git
    - git+https://github.com/aliutkus/torchsearchsorted.git
    - tornado==6.0.4
    - tqdm==4.43.0
    - traitlets==4.3.3
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0
